name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          # App (plain static files at repo root)
          app_location: "/"
          output_location: ""          # no build step for the app
          skip_app_build: true
          # API (managed Functions)
          api_location: "api"
          api_language: "node"         # 👈 tell SWA the runtime
          api_version: "18"            # 👈 Node 18 for managed API
          # (do NOT set skip_api_build: true — we want npm install to run)
